const express=require('express');
const signup = require('../controllers/signupcontroller');
const signin = require('../controllers/signincontroller');
const verifytoken = require('../controllers/verifytokencontroller');
const InController = require('../controllers/incontroller');
const OutController = require('../controllers/outcontroller');
const LeaveController = require('../controllers/leavecontroller');
const userProfileController = require('../controllers/userprofilecontroller');
const routes=express.Router();
routes.post('/signup',signup);
routes.post('/signin',signin);
routes.post('/intime',verifytoken,InController);
routes.post('/outtime',verifytoken,OutController);
routes.post('/leave',verifytoken,LeaveController);
routes.get('/userprofile',userProfileController);
module.exports=routes;